### ISSUE TITLE
Server available as well ?

### ISSUE THREAD

**Issue by hannesa2** [dizcza/MagneticViewer#1]
Interesting use case, do you have the server part as well ? I mean how do you publish the sensor data from Raspberry.

Btw, If you really want that I'll do a look why gesture is not working for you, you should open a ticket in my AndroidChart repo, I do not maintain dead MPAndroidChart

**Comment by dizcza** [comment]
I don't have the server in Android. It's server agnostic as long as it's set up to publish raw binary data.

For ESP32, I'm using their example https://github.com/espressif/esp-idf/tree/master/examples/protocols/sockets/tcp_server.

For Pi Pico, https://github.com/raspberrypi/pico-examples/tree/master/pico_w/tcp_server was used.

---

The issue I was having a few months ago is fixed in your fork. Cannot reproduce it now. So I've switched MPAndroidChart to your fork. Thanks for maintaining it.

---

I see you also set up MideaPipe to work on Android. Nice.

**Comment by hannesa2** [comment]
> I don't have the server in Android

Sure, the server is no Android stuff. But thanks for the pointers. In the past I did some websocket experiments. But I don't have that background knowledge, what's the benefit of TCPIP, so I want to see the code, maybe I understand then, what exactly TCPIP communication means.

> Cannot reproduce it now.

This is my issue too 😀

**Comment by hannesa2** [comment]
Btw, please clarify the situation here as well https://github.com/PhilJay/MPAndroidChart/pull/5302
